# Generated by Django 3.1.1 on 2022-03-25 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('hospital', '0002_auto_20220325_1442'),
        ('applicationForm', '0002_auto_20220325_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Photo')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('phone2', models.CharField(max_length=13, null=True, verbose_name='Phone 2')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_city', to='applicationForm.region', verbose_name='City / Region')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='department.department', verbose_name='Department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_district', to='applicationForm.district', verbose_name='District')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_hospital', to='hospital.hospital', verbose_name='Hospital')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_speciality', to='department.department', verbose_name='Speciality')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
