# Generated by Django 3.1.1 on 2022-03-25 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_speciality', to='department.speciality', verbose_name='Speciality'),
        ),
    ]
