# Generated by Django 3.1.1 on 2022-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20220325_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='post',
            field=models.IntegerField(choices=[(1, 'head'), (2, 'nurse'), (3, 'sanitary'), (4, 'physician')], default=4, verbose_name='Post'),
        ),
    ]
