# Generated by Django 3.1.1 on 2022-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='card_id',
            field=models.IntegerField(null=True, verbose_name='ID Card'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='post',
            field=models.IntegerField(choices=[(1, 'Head'), (2, 'Nurse'), (3, 'Sanitary'), (4, 'Physician')], default=4, verbose_name='Post'),
        ),
    ]
