# Generated by Django 4.0.3 on 2022-04-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('doctor', '0004_auto_20220326_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_floor', to='room.floor', verbose_name='Floor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_room', to='room.room', verbose_name='Room'),
            preserve_default=False,
        ),
    ]
