# Generated by Django 4.0.3 on 2022-04-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floor',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(verbose_name='Room')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_floor', to='room.floor', verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
            },
        ),
    ]
