# Generated by Django 4.0.3 on 2022-04-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20220325_1442'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reception_hospital', to='hospital.hospital', verbose_name='Hospital'),
            preserve_default=False,
        ),
    ]
