# Generated by Django 3.1.1 on 2022-03-25 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='City title')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='District')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/', verbose_name='Logo')),
                ('location', models.URLField(null=True, verbose_name='Location')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Phone')),
                ('phone2', models.CharField(max_length=100, null=True, verbose_name='Phone 2')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_city', to='hospital.city', verbose_name='City / Region')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_district', to='hospital.district', verbose_name='City / Region')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
