# Generated by Django 3.1.1 on 2022-03-26 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicationForm', '0002_auto_20220325_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(null=True, verbose_name='ID Card')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient/', verbose_name='Photo')),
                ('passport_serial', models.CharField(max_length=2, verbose_name='Passport Serial')),
                ('passport_number', models.IntegerField(verbose_name='Passport Number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('phone2', models.CharField(max_length=13, null=True, verbose_name='Phone 2')),
                ('work_place', models.CharField(max_length=255, null=True, verbose_name='Work Place')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender')),
                ('blood', models.IntegerField(choices=[(1, '(A+) A RhD positive'), (2, '(A-) A RhD negative'), (3, '(B+) B RhD positive'), (4, '(B-) B RhD negative'), (5, '(O+) O RhD positive'), (6, '(O-) O RhD negative'), (7, '(AB+) AB RhD positive'), (8, '(AB-) AB RhD negative')], verbose_name='Blood')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_city', to='applicationForm.region', verbose_name='City / Region')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_district', to='applicationForm.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
