# Generated by Django 4.0.3 on 2022-04-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationForm', '0002_auto_20220325_2215'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_city', to='applicationForm.region', verbose_name='City / Region'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_district', to='applicationForm.district', verbose_name='District'),
        ),
    ]
