# Generated by Django 4.0.3 on 2022-04-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_city_alter_patient_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.IntegerField(choices=[(1, '(A+) A RhD positive'), (2, '(A-) A RhD negative'), (3, '(B+) B RhD positive'), (4, '(B-) B RhD negative'), (5, '(O+) O RhD positive'), (6, '(O-) O RhD negative'), (7, '(AB+) AB RhD positive'), (8, '(AB-) AB RhD negative')], default=1, verbose_name='Blood'),
        ),
    ]
