# Generated by Django 4.0.3 on 2022-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID Card'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=25, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Surname'),
        ),
    ]
