# Generated by Django 3.1.1 on 2022-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationForm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'City / Region', 'verbose_name_plural': 'Cities / Regions'},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=128, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128, verbose_name='City'),
        ),
    ]
