# Generated by Django 3.2.12 on 2022-03-28 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(auto_now_add=True, verbose_name='End Hour'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(auto_now_add=True, verbose_name='Start Hour'),
        ),
    ]
