# Generated by Django 3.2.12 on 2022-03-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220326_1637'),
        ('timetable', '0005_receptiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminttance_type_doctor', to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Admittance Type',
                'verbose_name_plural': 'Admittance Types',
            },
        ),
        migrations.DeleteModel(
            name='ReceptionType',
        ),
    ]
