# Generated by Django 3.2.12 on 2022-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20220328_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittancetype',
            name='duration',
            field=models.IntegerField(max_length=120, verbose_name='Duration'),
        ),
    ]
