# Generated by Django 3.2.12 on 2022-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_admittancetype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittancetype',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Duration'),
        ),
    ]
