# Generated by Django 3.2.12 on 2022-03-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('timetable', '0010_admittance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminttance_patient', to='patient.patient', verbose_name='Patient'),
        ),
    ]
