# Generated by Django 3.2.12 on 2022-04-06 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0004_auto_20220326_1637'),
        ('timetable', '0011_alter_admittance_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at'),
        ),
        migrations.AddField(
            model_name='admittance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at'),
        ),
        migrations.AddField(
            model_name='admittancetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at'),
        ),
        migrations.AddField(
            model_name='admittancetype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_patient', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at'),
        ),
        migrations.AlterField(
            model_name='admittancetype',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Duration'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, verbose_name='(Monday) Start Hour')),
                ('monday_end', models.TimeField(blank=True, verbose_name='(Monday) End Hour')),
                ('tuesday_start', models.TimeField(blank=True, verbose_name='(Tuesday) Start Hour')),
                ('tuesday_end', models.TimeField(blank=True, verbose_name='(Tuesday) End Hour')),
                ('wednesday_start', models.TimeField(blank=True, verbose_name='(Wednesday) Start Hour')),
                ('wednesday_end', models.TimeField(blank=True, verbose_name='(Wednesday) End Hour')),
                ('thursday_start', models.TimeField(blank=True, verbose_name='(Thursday) Start Hour')),
                ('thursday_end', models.TimeField(blank=True, verbose_name='(Thursday) End Hour')),
                ('friday_start', models.TimeField(blank=True, verbose_name='(Friday) Start Hour')),
                ('friday_end', models.TimeField(blank=True, verbose_name='(Friday) End Hour')),
                ('saturday_start', models.TimeField(blank=True, verbose_name='(Saturday) Start Hour')),
                ('saturday_end', models.TimeField(blank=True, verbose_name='(Saturday) End Hour')),
                ('sunday_start', models.TimeField(blank=True, verbose_name='(Sunday) Start Hour')),
                ('sunday_end', models.TimeField(blank=True, verbose_name='(Sunday) End Hour')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_doctor', to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
    ]
