# Generated by Django 3.2.12 on 2022-04-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220326_1637'),
        ('patient', '0001_initial'),
        ('timetable', '0012_auto_20220406_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittancetype',
            name='duration',
        ),
        migrations.AddField(
            model_name='admittance',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='admittance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admittance_doctor', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='admittance',
            name='end_hour',
            field=models.TimeField(blank=True, verbose_name='End Hour'),
        ),
        migrations.AlterField(
            model_name='admittance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admittance_patient', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='admittance',
            name='start_hour',
            field=models.TimeField(blank=True, verbose_name='Start Hour'),
        ),
    ]
