# Generated by Django 3.2.12 on 2022-04-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_admittancetype_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittancetype',
            name='color_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color class'),
        ),
    ]
