# Generated by Django 4.0.3 on 2022-04-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_card_id_alter_patient_middle_name_and_more'),
        ('timetable', '0015_admittancetype_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittance',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admittance_patient', to='patient.patient', verbose_name='Patient'),
            preserve_default=False,
        ),
    ]
