# Generated by Django 4.0.3 on 2022-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_alter_admittance_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittancetype',
            name='color_class',
            field=models.CharField(choices=[('primary', '#0d6efd'), ('danger', '#dc3545'), ('secondary', '#6c757d'), ('success', '#198754'), ('warning', '#ffc107'), ('light', '#f8f9fa'), ('dark', '#212529')], default=1, max_length=100, verbose_name='Colors'),
        ),
    ]
