# Generated by Django 4.0.3 on 2022-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_rename_color_class_admittancetype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittance',
            name='color',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('admitting', 'Admitting'), ('admitted', 'Admitted')], default=('waiting', 'Waiting'), max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='admittancetype',
            name='color',
            field=models.CharField(choices=[('#0d6efd', 'primary'), ('#dc3545', 'danger'), ('#6c757d', 'secondary'), ('#198754', 'success'), ('#ffc107', 'warning'), ('#f8f9fa', 'light'), ('#212529', 'dark')], default=(('#0d6efd', 'primary'), ('#dc3545', 'danger'), ('#6c757d', 'secondary'), ('#198754', 'success'), ('#ffc107', 'warning'), ('#f8f9fa', 'light'), ('#212529', 'dark')), max_length=100, verbose_name='Colors'),
        ),
    ]
