# Generated by Django 4.0.3 on 2022-04-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_rename_color_admittance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admittance',
            options={'ordering': ['-id'], 'verbose_name': 'Admittance', 'verbose_name_plural': 'Admittances'},
        ),
    ]
