# Generated by Django 4.0.3 on 2022-04-10 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_floor_doctor_room'),
        ('timetable', '0022_alter_admittance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_doctor', to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Symptoms',
                'verbose_name_plural': 'Symptoms',
            },
        ),
    ]
