# Generated by Django 4.0.3 on 2022-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittance',
            name='symptoms',
            field=models.ManyToManyField(related_name='admittance_symptoms', to='timetable.symptoms', verbose_name='Symptoms'),
        ),
    ]
