# Generated by Django 4.0.3 on 2022-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_admittance_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittance',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='admittance_symptoms', to='timetable.symptoms', verbose_name='Symptoms'),
        ),
    ]
