# Generated by Django 4.0.3 on 2022-04-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_alter_admittance_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittance',
            name='diagnosis',
            field=models.TextField(null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='admittance',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='timetable.symptoms', verbose_name='Symptoms'),
        ),
    ]
