# Generated by Django 4.0.3 on 2022-04-11 02:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_admittance_diagnosis_alter_admittance_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittance',
            name='diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
