# Generated by Django 4.0.3 on 2022-04-10 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicationForm', '0003_alter_district_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Photo')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('phone2', models.CharField(max_length=13, null=True, verbose_name='Phone 2')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated_at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_city', to='applicationForm.region', verbose_name='City / Region')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_district', to='applicationForm.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Reception',
                'verbose_name_plural': 'Reception',
            },
        ),
    ]
