# Generated by Django 4.0.3 on 2022-04-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_nurse_delete_receptionist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurse',
            options={'verbose_name': 'Nurse / Orderly ', 'verbose_name_plural': 'Nurse / Sanitary'},
        ),
    ]
